---
output:
  html_document:
    df_print: paged
---
# Links

## Computer Graphics
* [Computer Graphics from Scratch](https://www.gabrielgambetta.com/computer-graphics-from-scratch/introduction.html)
* [Understanding Text Layout](https://www.oreilly.com/library/view/svg-text-layout/9781491933817/ch01.html)
* [Three.js for Learning Graphics Programming](https://threejs.org/)
* [Paper.js - Vector Graphics Scripting](http://paperjs.org/)
* [Font Rendering with Vector Textures](https://wdobbie.com/post/gpu-text-rendering-with-vector-textures/)
* [Ray Tracing in One Weekend](https://www.realtimerendering.com/raytracing/Ray%20Tracing%20in%20a%20Weekend.pdf)
* [Infinite Resolution Textures](https://research.nvidia.com/publication/infinite-resolution-textures)
* [Font Rendering Directly from Glyph Outlines](http://jcgt.org/published/0006/02/02/paper.pdf)
* [Data Driven Rendering: Pipelines](https://jorenjoestar.github.io/post/data_driven_rendering_pipeline/)
* [Scratchapixel](https://www.scratchapixel.com/)
* [Tiny Software Renderer](https://github.com/ssloy/tinyrenderer/wiki)
* [Physically Based Rendering](https://www.pbrt.org/)
* [Fast Fluid Dynamics Simulation on the GPU](https://developer.download.nvidia.com/books/HTML/gpugems/gpugems_ch38.html)
* [WebGL Fluid Simulation](https://github.com/PavelDoGreat/WebGL-Fluid-Simulation)
* [Idea for Gui from Scratch](https://www.reddit.com/r/learnprogramming/comments/214nd9/making_a_gui_from_scratch/)
* [Vulkan Tutorial](https://vulkan-tutorial.com/)
* [WebGPU Shading Language](https://gpuweb.github.io/gpuweb/wgsl.html)
* [ArrayFire - GPGU Library](https://arrayfire.com/the-arrayfire-library/)
* [Fix Your Timestep](https://gafferongames.com/post/fix_your_timestep/)
* [Making WebGL Dance](https://www.youtube.com/watch?v=GNO_CYUjMK8)
* [High Performance Graphics and Text Rendering on the GPU](https://www.youtube.com/watch?v=Xkpgsg6jU-4)
* [Using Rust for Game Dev](https://www.youtube.com/watch?v=aKLntZcp27M&t=1361s)
* [Rendering Vector Art on the GPU](https://developer.nvidia.com/gpugems/gpugems3/part-iv-image-effects/chapter-25-rendering-vector-art-gpu)
* [CGAL - Computational Geometry ALgorithms](https://www.cgal.org/)
* [ShaderToy](https://www.shadertoy.com/)
* [Text Rendering Hates You](https://gankra.github.io/blah/text-hates-you/)
* [Bresenham's Run Slice Line-drawing Algorithm](https://blog.demofox.org/2015/01/17/bresenhams-drawing-algorithms/)
* [the Beauty of Bresenham's Drawing Algorithm](https://news.ycombinator.com/item?id=15074080)
* [De Casteljeau's Algorithm](https://en.wikipedia.org/wiki/De_Casteljau%27s_algorithm)
* [SDL\_Universe - an Easy to Understand Software Renderer Written in SDL2](https://github.com/Semmu/sdl_universe)
* [CS Graphics Website/blog](http://iquilezles.org/)
* [Debug\_printf - Vulkan](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/debug_printf.md)
* [CS Graphics Courses](https://www.youtube.com/user/raviramamoorthi)
* [GPU Accelerated Path Rendering](http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/opengl/gpupathrender.pdf)
* [Drawing Thick Lines](http://kt8216.unixcab.org/murphy/index.html)
* [Line Rendering on the GPU](https://hero.handmade.network/forums/code-discussion/t/2188-line_rendering_on_the_gpu)
* [Drawing Lines Is Hard](https://mattdesl.svbtle.com/drawing-lines-is-hard)
* [Drawing Antialiased Lines with OpenGL](https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc)
* [Shader-Based Antialiased, Dashed, Stroked Polylines](http://jcgt.org/published/0002/02/08/)
* [Don't Fidget with Widgets, Draw! - Gui Performance](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.88.9094&rep=rep1&type=pdf)
* [Dynamically Switching Between Graphics APIs](https://gamedev.stackexchange.com/questions/157374/how-can-i-dynamically-switch-between-graphics-apis)
* [MDK - Curvy Blues: Drawing Bezier Curves](http://www.mdk.org.pl/2007/10/27/curvy-blues)
* [A Look At PathFinder](https://nical.github.io/posts/a-look-at-pathfinder.html)
* [2D Graphics on Modern GPUs](https://raphlinus.github.io/rust/graphics/gpu/2019/05/08/modern-2d.html)
* [Random-Access Rendering of General Vector Graphics](http://hhoppe.com/ravg.pdf)
* [Massively Parallel Vector Graphics](http://w3.impa.br/~diego/projects/GanEtAl14/)
* [FastUI Draw Technical Details 1](https://01.org/fast-ui-draw/blogs/krogovin/2016/fast-ui-draw-technical-details-1)
* [FastUI Draw Technical Details 1](https://01.org/fast-ui-draw/blogs/krogovin/2016/fast-ui-draw-technical-details-2)
* [Trapezoidal Decomposition](http://www0.cs.ucl.ac.uk/staff/m.slater/Teaching/CG/1997-98/Solutions/Trap/)
* [Triangulation By Ear Clipping](https://www.geometrictools.com/Documentation/TriangulationByEarClipping.pdf)
* [Introduction to Lyon: 2D Vector Graphics Rendering on the GPU in Rust](https://nical.github.io/posts/lyon-intro.html)
* [Bentley-Ottmann Algorithm](https://en.wikipedia.org/wiki/Bentley%E2%80%93Ottmann_algorithm)
* [Efficient Polygon Triangulation](https://flipcode.com/archives/Efficient_Polygon_Triangulation.shtml)
* [FIST: Fast Industrial-Strength Triangulation of Polygons](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.49.3013&rep=rep1&type=pdf)
* [Delaunay Triangulation](https://en.wikipedia.org/wiki/Delaunay_triangulation)
* [the State of Text Rendering](http://behdad.org/text/)
* [the State of Text Rendering in Linux](https://pandasauce.org/post/linux-fonts/)
* [Low Level Text Layout Kickoff](https://raphlinus.github.io/rust/skribo/text/2019/02/27/text-layout-kickoff.html)
* [GPU Resources](https://raphlinus.github.io/gpu/2020/02/12/gpu-resources.html)
* [Flattening Quadratic Beziers](https://raphlinus.github.io/graphics/curves/2019/12/23/flatten-quadbez.html)
* [Data Driven UIs, Incrementally](https://www.youtube.com/watch?v=R3xX37RGJKE)
* [Surfman - Rust](https://github.com/servo/surfman)

## Programming Languages
* [A High-level View of TLA+](https://lamport.azurewebsites.net/tla/high-level-view.html)
* [Kaleidoscope Tutorial](https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/index.html)
* [Chocopy](https://chocopy.org/)
* [A History of APL in 50 Functions](https://www.jsoftware.com/papers/50/)
* [Zen Programming Language](http://zenlang.sourceforge.net/)
* [Unison Programming Language](https://www.unisonweb.org/)
* [Basics of Compiler Design](http://hjemmesider.diku.dk/~torbenm/Basics/basics_lulu2.pdf)
* [ORC for Building JIT Compilers](https://llvm.org/docs/ORCv2.html)
* [Idris](http://docs.idris-lang.org/en/latest/tutorial/)
* [Regex Matching Can Be Simple and Fast](https://swtch.com/~rsc/regexp/regexp1.html)
* [Let's Build a Simple Interpreter](https://ruslanspivak.com/lsbasi-part1/)
* [Let's Build a Compiler](https://compilers.iecc.com/crenshaw/)
* [Selfie - Tiny C Compiler](https://github.com/cksystemsteaching/selfie)
* [Pipenv - Python Dev Workflow](https://pipenv-fork.readthedocs.io/en/latest/)
* [Poetry - Python Dev Workflow](https://python-poetry.org/)
* [A Half Hour to Learn Rust](https://fasterthanli.me/blog/2020/a-half-hour-to-learn-rust/)
* [Regex to DFA](https://cyberzhg.github.io/toolbox/nfa2dfa)
* [Dependent Type Systems As Macros](https://www.ccs.neu.edu/home/stchang/pubs/cbtb-popl2020.pdf)
* [Type Equality in LLVM](https://lowlevelbits.org/type-equality-in-llvm/)
* [AST Explorer](https://astexplorer.net/)
* [Build Your Own Webassembly Compiler](https://www.youtube.com/watch?v=OsGnMm59wb4&t=83s)
* [A Pretty But Not Greedy Pretty Printer](https://jyp.github.io/pdf/Prettiest.pdf)
* [A Pretty Printer - Philip Wadler](https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf)
* [the Hardest Program I've Ever Written - DartFMT](https://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/)
* [A Crash Course in Compilers](https://increment.com/programming-languages/crash-course-in-compilers/)
* [TypeScript Scanner](https://github.com/microsoft/TypeScript/blob/master/src/compiler/scanner.ts)
* [Why Parsing Tools Are Hard](http://blog.reverberate.org/2013/09/ll-and-lr-in-context-why-parsing-tools.html)
* [Dhall Configuration Language](https://dhall-lang.org/)
* [A Compiler Writing Journey](https://github.com/DoctorWkt/acwj)
* [Pratt Parsers](https://journal.stuffwithstuff.com/2011/03/19/pratt-parsers-expression-parsing-made-easy/)
* [Feral Lang](https://github.com/Feral-Lang/Feral)
* [Crafting Interpreters](https://www.craftinginterpreters.com/contents.html)
* [Hindley Milner Type System](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system)
* [Compiler for Arm Book](https://keleshev.com/)
* [What Every C Programmer Should Know About Undefined Behavior](http://blog.llvm.org/2011/05/what-every-c-programmer-should-know.html)
* [Micro C - a Compiler for a Subset of C for LLVM](https://blog.josephmorag.com/posts/mcc0/)
* [A New Architecture for Building Software](https://www.youtube.com/watch?v=b_T-eCToX1I)

## C++
* [Event Listener for GUI Lib - C++](https://codereview.stackexchange.com/questions/98564/event-listener-implementation)
* [Char + Char C++ Dark Corner](https://blog.knatten.org/2019/05/24/no-one-knows-the-type-of-char-char/)
* [Woboq Code Browser for C/C++](https://code.woboq.org/)
* [Audio Library - C++](https://www.kfrlib.com/)
* [Memory Order Explained](https://gcc.gnu.org/wiki/Atomic/GCCMM/AtomicSync)
* [Esoteric Data Structures and Where to Find Them](https://www.youtube.com/watch?v=-8UZhDjgeZU)
* [How I Declare My Class in C++ and Why](https://howardhinnant.github.io/classdecl.html)
* [Cpp-project-template](https://github.com/lefticus/cpp_starter_project)
* [Volatile - Multithreaded Programmer's Best Friend](https://www.drdobbs.com/cpp/volatile-the-multithreaded-programmers-b/184403766)
* [C++ 'You Can Do That' Moments'](https://www.reddit.com/r/cpp/comments/f6wlbm/what_arewere_your_favourite_you_can_do_that_neat/fiacu7w?utm_source=share&utm_medium=web2x)
* [C++ Quizzes](https://www.reddit.com/r/cpp/comments/5rbij8/c_quizzes/)
* [Solving Problems with STL](https://amp.reddit.com/r/cpp/comments/fantel/what_are_your_favourite_simple_solutions_for/)
* [COAT - C++ EDSL for JIT](https://github.com/tetzank/coat)
* [Klein - C++17 SIMD Geometry Library](https://github.com/jeremyong/klein)
* [Handling Asynchronous Requests Using Futures - C++](http://www.mycpu.org/c++-threads-async-deferred/)
* [C++ Memory Model - an Intuition](https://www.youtube.com/watch?v=OyNG4qiWnmU)
* [Hardware Effects - C++](https://github.com/Kobzol/hardware-effects)
* [Mimalloc - Microsoft](https://github.com/microsoft/mimalloc)
* [QtQuick Custom Item Performance](https://www.vikingsoftware.com/qtquick-custom-item-performance/)
* [Getting Rid of Volatile in (some Of) Qt](https://www.kdab.com/getting-rid-of-volatile-in-some-of-qt/)
* [the Performance Benefits of Final Classes](https://devblogs.microsoft.com/cppblog/the-performance-benefits-of-final-classes/)
* [C++ Standard - Draft](https://eel.is/c++draft/)
* [Data Oriented Design and C++](https://www.youtube.com/watch?v=rX0ItVEVjHc&t=4651s)
* [So, You Inherited a Large Codebase...](https://www.youtube.com/watch?v=B2XtqVZcSdM&t=14s)
* [Local 'arena' Memory Allocators](https://www.youtube.com/watch?v=nZNd5FjSquk&t=2078s)
* [How We Get to Main](https://www.youtube.com/watch?v=dOfucXtyEsU&t=1268s)
* [Rust: Hack Without Fear](https://www.youtube.com/watch?v=lO1z-7cuRYI&t=2s)
* [Is C++ Context-free Or Context-sensitive?](https://stackoverflow.com/a/14589567)
* [C++ Annotations](http://www.icce.rug.nl/documents/cplusplus/)
* [Wait-Free Queue](https://www.boost.org/doc/libs/1_72_0/doc/html/atomic/usage_examples.html#boost_atomic.usage_examples.example_ringbuffer)
* [Rocket - Alternative to Boost Signals](https://github.com/tripleslash/rocket)
* [Constexpr Function Parameters](https://mpark.github.io/programming/2017/05/26/constexpr-function-parameters/)
* [Compile-time Finite State Machine](https://philippegroarke.com/posts/2020/constexpr_fsm/)
* [Fun with Std::threads](https://philippegroarke.com/blog/2015/08/21/fun-with-stdthreads/)
* [SIMD - Understanding 16 Byte Memory Alignment Detection](https://philippegroarke.com/blog/2017/02/19/quicktip-understanding-16-byte-memory-alignment-detection/)
* [List of C++ UI Libraries](https://philippegroarke.com/posts/2018/c++_ui_solutions/)
* [Dead Simple Markov Sentences](https://github.com/p-groarke/deadsimplemarkovsentences)
* [How to SIMD](https://github.com/p-groarke/cppmtl_howtosimd/blob/master/src/main.cpp)
* [Compiler-neutral Internal Program Representation for C++](https://github.com/GabrielDosReis/ipr)
* [Run-vcpkg Github Actions](https://github.com/marketplace/actions/run-vcpkg)
* [Boyer\_moore\_searcher with the Rytter Correction](https://github.com/microsoft/STL/pull/724)
* [A Principled, Complete, and Efficient Representationof C++](http://www.stroustrup.com/macis09.pdf)
* [CPM - CMake Package Manager](https://github.com/TheLartians/CPM.cmake)
* [Obfuscated C Primer](https://github.com/ColinIanKing/christmas-obfuscated-C/blob/master/tricks/obfuscation-tricks.txt)
* [Correctly Implementing a Spinlock in C++](https://rigtorp.se/spinlock/)

## Computer Science
* [Embarrassingly Parallel](https://en.wikipedia.org/wiki/Embarrassingly_parallel)
* [D\* Lite Path Finding](http://idm-lab.org/bib/abstracts/papers/aaai02b.pdf)
* [Continuum Crowds](https://grail.cs.washington.edu/projects/crowd-flows/78-treuille.pdf)
* [What Every Programmer Should Know About Memory](https://people.freebsd.org/~lstewart/articles/cpumemory.pdf)
* [Optimizing File Access Via Ordering and Caching](http://wassenberg.dreamhosters.com/articles/study_thesis.pdf)
* [VNC Data Compression Algorithm](http://www.iiisci.org/journal/CV$/sci/pdfs/P841078.pdf)
* [Ryu Algorithm for Float to String Conversion](https://github.com/ulfjack/ryu)
* [Functional Description of Tex Formula Layout](https://people.eecs.berkeley.edu/~fateman/temp/neuform.pdf)
* [Programming Trick Questions](https://qntm.org/trick)
* [B-Tree](https://en.wikipedia.org/wiki/B-tree)
* [Design Patterns for Low-level Real Time Rendering](https://www.youtube.com/watch?v=mdPeXJ0eiGc)
* [CPU Caches and Why You Care](https://www.youtube.com/watch?v=WDIkqP4JbkE)
* [What Every Programmer Should Know About Memory](https://people.freebsd.org/~lstewart/articles/cpumemory.pdf)
* [Full Stack Course University of Helsinki](https://fullstackopen.com/en/)
* [Interactive Guide to Buffer Overflow Eploitation](https://nagarrosecurity.com/blog/interactive-buffer-overflow-exploitation)
* [an Efficient Unification Algorithm](http://moscova.inria.fr/~levy/courses/X/IF/03/pi/levy2/martelli-montanari.pdf)
* [ISPC - Intel SPMD Program Compiler - SIMD Lang](https://github.com/ispc/ispc)
* [Teddy - SIMD Accelerated Substring Matching Algorithm](https://github.com/jneem/teddy)
* [SIMD Instructions - Open Source Weekly](https://news.ycombinator.com/item?id=22833299)
* [Is\_sorted Using SIMD](http://0x80.pl/notesen/2018-04-11-simd-is-sorted.html)
* [Nand2Tetris - Computers from Scratch](https://www.nand2tetris.org/)
* [Architecture of Open Source Applications](https://aosabook.org/en/index.html)
* [MQTT - IoT Protocol](http://mqtt.org/)
* [CRDT - Conflict Free Replicated Data Type](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type)
* [Meyers Diff Algorithm](https://blog.robertelder.org/diff-algorithm/)

## OS
* [Sel4 - Formally Verified Kernel](https://sel4.systems/)
* [Genode: Non-POSIX Os Framework](https://genode.org/)
* [Learn Emulator Development](https://www.reddit.com/r/EmuDev/comments/easb84/whats_the_best_way_to_learn_emulator_development/)
* [OSDev](https://wiki.osdev.org/Expanded_Main_Page)
* [How Are UNIX Pipes Implemented?](https://toroid.org/unix-pipe-implementation)
* [Implementing an OS in Rust Uni Course](https://tc.gts3.org/cs3210/2020/spring/lab.html)

## Text editors
* [RRB-Tree for Text Editors](https://public.sinusoid.es/misc/immer/immer-icfp17.pdf)
* [Data Structure for Text Style](https://stackoverflow.com/questions/4185624/most-efficient-data-structure-to-add-styles-to-text/4197146)
* [Data Structures for Text Editors - Crowley](https://www.cs.unm.edu/~crowley/papers/sds.pdf)
* [Making Neovim Plugins with Lua](https://dev.to/2nit/how-to-write-neovim-plugins-in-lua-5cca)
* [Efficient Data Structure for a Hex Editor](https://www.chiark.greenend.org.uk/~sgtatham/tweak/btree.html)
* [A Brief Glance At How Various Text Editors Manage Their Textual Data](https://news.ycombinator.com/item?id=16385440)
* [Breaking Paragraphs Into Lines](http://www.eprg.org/G53DOC/pdfs/knuth-plass-breaking.pdf)
* [Rope Science - Xi Editor](http://abishov.com/xi-editor/docs/rope_science_00.html)

## Browsers
* [Chrome University](https://www.youtube.com/watch?v=kNzoswFIU9M&list=PLNYkxOF6rcICgS7eFJrGDhMBwWtdTgzpx)
* [LexBor HTML 'renderer'](https://github.com/lexbor/lexbor)
* [Flex Layout Algorithm](https://www.w3.org/TR/css-flexbox-1/#layout-algorithm)
* [Grid Layout Algorithm](https://www.w3.org/TR/css-grid-1/#auto-placement-algo)
* [Pathfinder - GPU Rasterizer for Fonts and Vector Graphics](https://github.com/servo/pathfinder)
* [How to Manage HTML DOM](https://htmldom.dev/)
* [Using Hugo and Gitlab Pages to Make a Website](https://tkainrad.dev/posts/using-hugo-gitlab-pages-and-cloudflare-to-create-and-run-this-website/)
* [Drag and Drop with Vanilla JS](https://blog.soshace.com/the-ultimate-guide-to-drag-and-drop-image-uploading-with-pure-javascript/)
* [Overconstrained.io - Cassowary Algorithm](http://overconstrained.io/)
* [Comments with Github Issues](https://aristath.github.io/blog/static-site-comments-using-github-issues-api)
* [CSS for Internationalization](https://www.chenhuijing.com/blog/css-for-i18n/)
* [Jargon](https://wiki.mozilla.org/Platform/GFX/Jargon)
* [Gecko Overview](https://wiki.mozilla.org/Gecko:Overview)
* [Dawn - Chromium's WebGPU Implementation](https://dawn.googlesource.com/dawn)
* [Layout Engines for Web Developers](https://www.youtube.com/watch?v=a2_6bGNZ7bA)

## Databses
* [Writing a Databse from Scratch in Go](https://notes.eatonphil.com/database-basics.html)
* [Crux Database Using Datalog](https://opencrux.com/)
* [How Doeas a Relational Database Work](http://coding-geek.com/how-databases-work/)
* [Datalog - SQL Alternative](https://en.wikipedia.org/wiki/Datalog)
* [Relational Algebra](https://en.wikipedia.org/wiki/Relational_algebra)
* [How Io\_uring and EBPF Will Revolutionize Programming in Linux](https://thenewstack.io/how-io_uring-and-ebpf-will-revolutionize-programming-in-linux/)
* [Let's Bulid a Database - SQLite Clone from Scratch in C](https://cstack.github.io/db_tutorial/)

## Math
* [Linear Algebra Book](http://joshua.smcvt.edu/linearalgebra/book.pdf)
* [All in One Math Cheatsheet](https://ourway.keybase.pub/mathematics_cheat_sheet.pdf)
* [Applications of Linear Algebra](https://kam.mff.cuni.cz/~matousek/stml-53-matousek-1.pdf)

## AI
* [Fastai - Neural Nets](https://www.fast.ai/)
* [Lossless Image Compression Through Super Resolution](https://github.com/caoscott/SReC)
* [Learning to See in the Dark](https://github.com/cchen156/Learning-to-See-in-the-Dark)
* [Andrew Ng - Machine Learning](https://en.wikipedia.org/wiki/Andrew_Ng)
* [Adversarial Latent AutoEncoders](https://github.com/podgorskiy/ALAE)

## VCS
* [Write Yourself a Git](https://wyag.thb.lt)
* [Isomorphic-git](https://github.com/isomorphic-git/isomorphic-git)
* [Pijul](https://nest.pijul.com/pijul_org/pijul)

## Misc
* [Learning Music](https://learningmusic.ableton.com/chords/1-5-6-4.html)
* [OnlyOffice](https://www.onlyoffice.com/)
* [Build-your-own](https://github.com/danistefanovic/build-your-own-x)
* [RMarkDown Basics](https://rmarkdown.rstudio.com/authoring_basics.html)
* [RMarkDown Basics - More](https://cran.r-project.org/web/packages/stationery/vignettes/Rmarkdown.pdf)
* [Arrow Operator in Apple Docs](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6.html#ScalerTypeNote)
* [Mapping Resposibly](https://www.esri.com/arcgis-blog/products/product/mapping/mapping-coronavirus-responsibly/)
* [Javidx9](https://www.youtube.com/channel/UC-yuWVUplUJZvieEligKBkA)
* [3blue1brown](https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw)
* [Ben Eater](https://www.youtube.com/user/eaterbc)
* [Comparison of Voting Schemes Security](https://www.attejuvonen.fi/thesis/)
* [ContextFree](https://www.youtube.com/channel/UCS4FAVeYW_IaZqAbqhlvxlA)
* [Why Open Source Matters for Government and Civic Tech(and How to Support It](https://rufuspollock.com/open-source-software-and-government/)
* [Talkyard - Forum Software Combining Best of SO, Discourse, Slack, HN/Reddit, Disqus](https://github.com/debiki/talkyard)
* [Jami - GNU Open Source End-to-end Encrypted Alternative to Zoom/Jitsi](https://news.ycombinator.com/item?id=22755596)
* [Matrix - Decentralized Communication](https://matrix.org/)
* [Hilarious NixOS Github Issue](https://github.com/NixOS/nixpkgs/issues/4952)
* [WasyPrint - Nice Document Formatter](https://weasyprint.org/)
* [John Conway Memorial](https://terrytao.wordpress.com/2020/04/12/john-conway/)
* [John Conway Memorial 2](https://github.com/nixpulvis/doomsday)
* [ArduBee - Open Source Drone](https://discuss.ardupilot.org/t/ardubee-a-ready-to-fly-micro-drone-for-education-and-swarming/54362)
* [IOS on QEMU](https://github.com/alephsecurity/xnu-qemu-arm64)
* [Software Engineer Going Blind](https://news.ycombinator.com/item?id=22918980)
* [OpenHAB - Open Source Home Automation](https://www.openhab.org/)
* [How the Economic Machine Works](https://www.youtube.com/watch?v=PHe0bXAIuk0)
* [Patch Workflow with Mutt](http://kroah.com/log/blog/2019/08/14/patch-workflow-with-mutt-2019/)
* [Engineering Code Quality in Firefox](https://hacks.mozilla.org/2020/04/code-quality-tools-at-mozilla/)
* [Home Assistant - Open Source Home Automation](https://www.home-assistant.io/)
* [OpenMediaVault - Open Source NAS](https://www.openmediavault.org/)

## Books

* C++ concurrency in action
